export enum Role {
    ROLE_MANAGER = 'ROLE_MANAGER',
    ROLE_OPERATOR = 'ROLE_OPERATOR',
    ROLE_DATA = 'ROLE_DATA',

    ROLE_SERVER_REST_ACCESS = 'ROLE_SERVER_REST_ACCESS',
    ROLE_ASSET_REST_ACCESS = 'ROLE_ASSET_REST_ACCESS',
    ROLE_BILLING = 'ROLE_BILLING',

    ROLE_MASTER_ADMIN = 'ROLE_MASTER_ADMIN',
    ROLE_MASTER_OPERATOR = 'ROLE_MASTER_OPERATOR',
    ROLE_MASTER_SUPPORT = 'ROLE_MASTER_SUPPORT',
    ROLE_ADMIN = 'ROLE_ADMIN'
}